
import discord
import io
from datetime import datetime

async def generate_transcript(channel):
    """Generate a transcript of a ticket channel"""
    transcript_content = f"Generated by SereneEnterprise, all rights reserved (c) (Taken from Almora Retail)\n"
    transcript_content += f"Transcript for {channel.name}\n"
    transcript_content += f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC\n"
    transcript_content += "=" * 50 + "\n\n"
    
    async for message in channel.history(limit=None, oldest_first=True):
        timestamp = message.created_at.strftime('%Y-%m-%d %H:%M:%S')
        author = f"{message.author.display_name} ({message.author})"
        content = message.content if message.content else "[No text content]"
        
        # Handle embeds
        if message.embeds:
            for embed in message.embeds:
                if embed.title:
                    content += f"\n[EMBED] {embed.title}"
                if embed.description:
                    content += f"\n{embed.description}"
        
        # Handle attachments
        if message.attachments:
            for attachment in message.attachments:
                content += f"\n[ATTACHMENT] {attachment.filename}"
        
        transcript_content += f"[{timestamp}] {author}: {content}\n"
    
    # Create a file-like object
    transcript_file = io.StringIO(transcript_content)
    return discord.File(transcript_file, filename=f"{channel.name}-transcript.txt")

def get_ticket_info_from_channel(channel):
    """Extract ticket information from channel name and topic"""
    ticket_owner = None
    claimed_by = None
    
    # Get owner from channel name
    if channel.name.startswith("ticket-"):
        owner_name = channel.name.replace("ticket-", "")
        # Try to find the user
        for member in channel.guild.members:
            if member.name.lower() == owner_name:
                ticket_owner = member
                break
    
    # Get claimed info from topic
    if channel.topic and "Claimed by:" in channel.topic:
        claimed_by = channel.topic.replace("Claimed by: ", "")
    
    return ticket_owner, claimed_by
